name: "Laravel + Vue Setup"
description: "Initial setup for Laravel 12 with Inertia.js and Vue 3"
title: "[Setup] "
labels: ["setup", "laravel", "vue"]
body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Initialize a new Laravel 12 project using Inertia.js + Vue 3.
        Set up environment, configure API key, and test HTTP client.

        ## Acceptance Criteria
        - Laravel + Vue app running locally
        - SpaceTraders API key stored securely
        - Basic test route fetches agent info

        ## Subtasks
        - [ ] Install Laravel (`laravel new spacetraders-control --kit=vue`)
        - [ ] Run `php artisan serve` + `npm run dev`
        - [ ] Add `SPACETRADERS_API_KEY` in `.env`
        - [ ] Create `SpaceTradersApi` service
        - [ ] Create route `/test-agent` → Inertia Vue page showing API response
        - [ ] Push repo to GitHub
